function pretty()
set(groot,'defaultAxesLineWidth',1.0,...
          'defaultAxesFontSize',12,...
          'defaultLineLineWidth',1.5,...
          'defaultLegendBox','off',...
          'defaultFigureColor','w');
end
